// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccquallmhybptgstaeqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjcXVhbGxtaHlicHRnc3RhZXFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NTQ2MDAsImV4cCI6MjA2OTAzMDYwMH0.vUkJfssryY2aZ17dCw6OoWp8v1FME35OH-ED-87_3BU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});